#!/bin/sh
set -e
cd "$(dirname "$0")/source"

git -C cachy fetch origin master
git -C cachy reset --hard origin/master
git -C xanmod fetch origin master
git -C xanmod reset --hard origin/master
# git -C zfs # Manually update
# git -C nvidia # Manually update
# git -C bcachefs
